import "./globals.css";

export const metadata = {
  title: "Cultural Calendar App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* You can add a Navbar here if you want it on every page */}
        {children} 
      </body>
    </html>
  );
}